addons:
  code_climate:
    repo_token: "$$CODE_CLIMATE_TOKEN$$"

language: php

sudo: false

php:
    5.5
    5.6
    hhvm

before_script:
    - composer install --dev --prefer-source

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - 'curl -X POST -d @codeclimate.json -H "Content-Type: application/json" -H "User-Agent: Code Climate (PHP Test Reporter v1.0.1-dev)"  https://codeclimate.com/test_reports'
